/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AgentNodeCards: typeof import('./components/AgentNodeCards.vue')['default']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ChartCard: typeof import('./components/analysis/ChartCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HitlApprovalBar: typeof import('./components/HitlApprovalBar.vue')['default']
    InterruptCard: typeof import('./components/InterruptCard.vue')['default']
    MessageBubble: typeof import('./components/MessageBubble.vue')['default']
    ReportMarkdown: typeof import('./components/analysis/ReportMarkdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolCallItem: typeof import('./components/ToolCallItem.vue')['default']
    ToolCallSteps: typeof import('./components/ToolCallSteps.vue')['default']
  }
}
